# import './Lyon/Deliverfile'

config = File.expand_path('../../', __FILE__)
$LOAD_PATH.unshift(config) unless $LOAD_PATH.include?(config)
require 'aBike.rb'

def copyDeliverfile

	deliverFile = File.expand_path File.dirname(__FILE__)

	deliverFile += "/Deliverfile"

	if File::exists?(deliverFile)
		copiedPath = Dir.pwd + "/Deliverfile"
		FileUtils.cp deliverFile, copiedPath
	else
		puts "doesn't exist"
		raise "Deliverfile doesn't exist at path " + deliverFile
	end

end

def deleteDeliverfile

	copiedPath = Dir.pwd + "/Deliverfile"

	if File::exists?(copiedPath)

		FileUtils.rm copiedPath

	end

end

private_lane :lyon_appstore do

	gym(
	     workspace: "aBike—Lyon.xcworkspace",
	     scheme: "aBike—Lyon",
	     clean: true,
	     configuration: "Release",
	     include_bitcode: true,
	     export_team_id: "W48L6Z4654",
		 output_directory: "./build",
		 output_name: "aBike—Lyon",
		 export_method: "app-store"
	)

	copyDeliverfile

	deliver

	deleteDeliverfile

end
