language: objective-c
osx_image: xcode7.2
podfile: Podfile
cache: cocoapods
sudo: false
matrix:
    include:
        - env:
            - VESIMULATOR_SDK=iphonesimulator9.2
            - VESIMULATOR_VERSION=9.2
        - env:
            - VESIMULATOR_SDK=iphonesimulator9.1
            - VESIMULATOR_VERSION=9.1
before_install:
    - pod install
script:
    - xctool build test -sdk $VESIMULATOR_SDK -destination 'platform=iOS Simulator,name=iPhone 5s,OS=$VESIMULATOR_VERSION'
xcode_workspace: aBike—Lyon.xcworkspace
xcode_scheme: aBikeFramework
