language: objective-c
osx_image: xcode7.2
podfile: Podfile
cache: cocoapods
sudo: true
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROFILE_NAME="Travis_Provisioning_Profile"
  - 'DEVELOPER_NAME="iPhone Developer: Clement Padovani (L4ZPL65Y4M)"'
  - secure: "Lxhe+tqxwj7t0eYGuz0x6hiyNeMRsK1u9FlLY7jMBEWblr5Dqa06iUB8/pezE1I18HdOw5CFmgJfQJ/QQQNhdZn9tmJ/EgWrKLspIeHCZmXZn7c0a1Fxuy5yo2/r3NOCFUGnnsBOOgpDk7YTtebQ/6pwDh8cogej/XWzU/OItfxW7O6AkOkagCKseALBxPdTl9y8KcDTMk5b16xyuEWyM5vmC6wWWGBKySARj8A3CnVBlpbKoq9798vY9CKqtV4MpcwXeYvwUf641K4EqjeJE944k3eUQMH4e4kIP++jeBT7QS9SDmt2mj0geRu/AQuG1S0bcIiVBJ3Qio2ADlmUdoP6fBbje6GVaSCv2yXjRAAfbcaYY+QLp68441hMFV05/WqtKgaz2Kh3MjyM5Mtaot7mOW94hwzTmIKdjfvd8fGXFtiAJdodPdkx2nI535+dGnaDFY9dXz9hYWjZPe/6ytRvzYVWy6FA1Mlibi/ZthgP9uBwIUerjeiCYilS2zuOF0zEPrS26DP5QSohbMrXSpFsZdHNIy8qOxphh7a5R+lfkDfOEnNDwPKWHFCmin87dT39xmJt8dItTzK/DXnqCWDb8ji7hICs6/KcVRc1iwCWijOEofntWtrp63xziWj3vyPjIz3bIRjj9NZm3mg6K9nI7jwFaiNbPMxCinr7plM="
  - secure: "qTmQnBvL1k97jSZohzT0wU75OXgafum6couLV7gBUG/CyzduUIMMgSYMHto7/m2h6opDdBLoVTjb5MPxYzGJpVTTtgnYJwaT60ZmSBzTutflg2a36V95wOlWfy2p/E+vl3hzatQEGn64oZ9n8sY0gNXt7MTHiyMSQduTvRaT3msBY/In3b/A7B2B/lvkHFkurJuE6OERvSukbTYliEAzwmkuatY2EplieHRkXMQY346I3logwzzcHd43LtobD7IJGmoKmrPI2Pb2tUNmJjqoow+ZWs60wc7nS3eR7Dq6Uy322i67LLCA1t/wInBzPc5GBgVbGje9bSdgbCat6kMWoH/JJspHLZ1Yw0lyBmHyPf0gDnMKs5GeeZH++ZcjKIsdM5H0vluZlwqsPKqUF+hTG5LdrN5vsBsvnWhDa7pOY/GVGXUX91+qn9kPQSN2vTcM1wDW/hhiHyTu+ar1OjUVD/etFraHkWGQuH26H1rxiaDUeA4bcoHL0cx3lDrnoI8718RIUb9wOiZJ+HOr478NrPbQPGBmIh0LFeg9kkee8tOnQoHcsqjVtWIrMhio4Nh9pm+tCGZaapun2HpVXMpbuOETQVzIIr2xrygdvt2UOUJXA7xZqVm/1OJnlCUH3jh9dTCJiNHmjrDbiDuXShJ/yU81/rsafLTmzcf5hmG34yU="
before_script:
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in Vendor/Travis_Provisioning_Profile.mobileprovision.enc -d -a -out Vendor/Travis_Provisioning_Profile.mobileprovision
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in Vendor/certificate.cer.enc -d -a -out Vendor/certificate.cer
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in Vendor/key.p12.enc -d -a -out Vendor/key.p12
    - "./Vendor/add-key.sh"
script:
    - xctool test -sdk iphonesimulator9.2 -destination 'platform=iOS Simulator,name=iPhone 5s,OS=9.2'
after_script:
    - "./Vendor/remove-key.sh"
