sudo: false
language: objective-c
osx_image: xcode7.3
matrix:
    include:
        - osx_image: xcode7.2
          env: CP_IOS_SIMULATOR="iphonesimulator9.2" CP_IOS_SIMULATOR_OS="platform=iOS Simulator,name=iPhone 5s,OS=9.2"
        - osx_image: xcode7.1
          env: CP_IOS_SIMULATOR="iphonesimulator9.1" CP_IOS_SIMULATOR_OS="platform=iOS Simulator,name=iPhone 5s,OS=9.1"
        - osx_image: xcode7
          env: CP_IOS_SIMULATOR="iphonesimulator9.0" CP_IOS_SIMULATOR_OS="platform=iOS Simulator,name=iPhone 5s,OS=9.0"
podfile: ./Podfile
os: osx
cache: cocoapods
env:
    global:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8
        - PROFILE_NAME="Travis_Provisioning_Profile"
    matrix:
        - CP_IOS_SIMULATOR="iphonesimulator9.3" CP_IOS_SIMULATOR_OS="platform=iOS Simulator,name=iPhone 5s,OS=9.3"
before_install:
    - env
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in Vendor/Travis_Provisioning_Profile.mobileprovision.enc -d -a -out Vendor/Travis_Provisioning_Profile.mobileprovision
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in Vendor/certificate.cer.enc -d -a -out Vendor/certificate.cer
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in Vendor/key.p12.enc -d -a -out Vendor/key.p12
    - ./Vendor/add-key.sh
    - ./Vendor/add-constants.sh
script:
    - xctool test -sdk $CP_IOS_SIMULATOR -destination "$CP_IOS_SIMULATOR_OS"
after_script:
    - ./Vendor/remove-key.sh
    - ./Vendor/remove-constants.sh
    - sleep 3
