language: objective-c
osx_image: xcode7.2
podfile: Podfile
cache: cocoapods
sudo: true
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROFILE_NAME="Travis Provisioning Profile"
  - 'DEVELOPER_NAME="iPhone Developer: Clement Padovani (L4ZPL65Y4M)"'
  - secure: WCRdx2XVoS8v2kvJVMYYwP2B12KWlEfv5bX9eUxKfLLZKj/OkuF/HF0A3giaZ2stn7fF3ipfzNlYFUv6sfuMdQyPH8IAW8NqbWYKFxxd11YBVNeExwEOgrEEkOEuf64MKIHN4F9P0WtZxeCakVqkdnjRVoRV47mZtsQrGPCjjILOx9k0xrRvwp9SCZdF3VD6cLcT1aRrZU+X4T2gfIZU+rwkGoB+W3+LgpwUmFLGxCiwu27V08CqM6x2rA5HwpStrdhs/60xiWXDfZZJfGepq8fzsC6WgRVdun3r15z8nE/21InRqH1NDLZy/4w+9TPfL24hOezcfePS5vbm1Lu6+TrV1IjKpkxzJU4mvgC7aNN9OYy3rz64Tzlg98iYltG03p+KhGpmc4xlFPn83wvThuSDIJ6TvBEf29ARRpsvsiKQyOGEHq5zIXFWCBW0Bcyo9fYknN6ATbKMbinwoJRiZ+2+UfNb7GmVxlrhFUdW7sRjV0P+pfCAtbcwi5GTu25JQCZ55ifikPwcbcADdiv2zjDpTsEqLJbWsh9i4eDg5EUml0xQNPaky2Rtgg8BHmvaVle+k3/zOsX8b85VdDhJvD85VZh+xFJ55OidhYWQK3g8I7KoDNqYtR1UsaPXNRv0/1YGcGYj1hn1K5wA0eMFTZTOR4SpGp235Gb2THE+7zQ=
  - secure: SkV/n+gkc/1oJlJPU2f026qlFdpQumKyITaE5KaO7PR53lbt6xZevRiMlGc/c8fPKQIiodbmWJqE1xkJuUQqU0o/djskPdJg7jBX2H/M0rPJ/Q0aAUabeGqgsj0N+N820qeMAKdZ+oY+zZv4fk7eQKq8Bu6Lbm8dQ1+aOUzz67H3T3tpWQjzh6igBEWN+DSXDoxaPVu2e+JAW/VEKcZpGp86inr3Olx3X6pFvie1pE600LzJBbH1Z5c8lpIlHzXloYZvOyU04+cb6Uq6mfte3fDLgy1qdTinlREsdJwJZUyG+gb/zaw5y4Si1mgVFP45KMXvR0RnV7xB+1g4g4n9qhJSXtNJ0jOkJRRu0+RzTDlNq9bhUFx6J/VfcM3jJkSWEH0JNXsIIHWRYJJz1iLEg4PRK06cEN0hUiHQ0E2MsmZSYtN7Jwdk0/LlRwS4Uck/IWl96B1wqYGjuwMgcmQXSHruuYKxOzHKrCpoxzrg9pRm2+3Fy9klPT/7Zm9Wxh3cFAABbd4IzRXQVcy3aG7dVSqQ8NTZPTzzgDRnQ2N6qHSmPGiM6nvmxdkdRgUxWkbUeuE8mVXxjxqOYWRPXwa+eQwD3hWUsP63PyEU2M5gaMC75iRVdfU7H+T2geCs2Vfo9i+eZGpxYWrH4yajI14wDhjO87x3yIBZ5ByZ74XBet0=
  - secure: "vE1BY1LKO9KZcbuayWi+WvH6ccJhFzwemCtjV1E1eM0GEO5qQJSN6Oc8dvvis/fzjNTeAtww7DA2xCfQ39TAhllQSGO1QitHa9Bkyjr7gcqubPu6qG0vdD+XicwOudXvFY97MlZhs1pNDBHmNV6Kh1xSQQVHgB6yAEth+e4DEnJXz6lCybgXFRRgGLfWbltdNPhH/GqNn0Me7bb9bjYOnE0L66q9/I8lC/Yp3l/wlzeXLD99qrlcreJyDBFNJnzoQoLqHtxUsCh+aos34XnBTmd1KuChBsBjtbiUWKeOZJFD5AS10wz35AXSLTwKTSVtfcmpXMzMe+zl66zISUWrDfBMYPkXfDGZtdPB39oBV0eg2goFP/VRf9OE7/k3oGlFzPgwqNif8m69zPHbewx5dReAy67q/j8qSVfpdIsySoaOBY6LaFd8YCDdhUk+CkzvNHjosTZTGcDU2qVwP7oi7Oys4gcUmCjUeAhsuMoplxcBG90x8oEihfD3SQ6qBHUmitz8QAqnJ478ve9Ut82W6K1JQO4C0y89B/ui0uhk/JB9uMm12XrULhkVjilMDvGoqlXZ/sGJOhsSw673sTULuJYzGke6Aqws7EhODbNP+yvSjuJkvmOnKlHFxiK3p16HNO1oNNboFwnrQckHj4BTy0gdraRNC7JQHrpTWnr6D24="

before_script:
    - echo $ENCRYPTION_SECRET
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in Vendor/Travis_Provisioning_Profile.mobileprovision.enc -d -a -out Vendor/Travis_Provisioning_Profile.mobileprovision
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in Vendor/Certificate.cer.enc -d -a -out Vendor/Certificate.cer
    - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in Vendor/key.p12.enc -d -a -out Vendor/key.p12
    - ./Vendor/add-key.sh

script:
    - xctool "build test -sdk iphonesimulator9.2 -destination 'platform=iOS Simulator,name=iPhone5s,OS=9.2'"

after_script:
    - ./Vendor/remove-key.sh
