language: objective-c
osx_image: xcode7.2
podfile: Podfile
cache: cocoapods
sudo: true
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROFILE_NAME="Travis Provisioning Profile"
  - 'DEVELOPER_NAME="iPhone Developer: Clement Padovani (L4ZPL65Y4M)"'
  - secure: JB9ctsgpgxwtfddlXAUPwMMyQk8ye1/7HIHpsWMJlvyYN3MIP9IiR2YUTF2YUb/kj37RXl7I+aQ8u9H18ythF8fPSCVuUa775XY9HEY5YTc/1mt66b9lPamZfCEfQ0+JGV9Tx5gzN8lhQ4MdL6IScSRgJpuvCHWI0/7boW+8REdDRPiy5gIBuHd3F35WaqT/iyewrPfMSryAvBE/9ujKha4uuvVWehmADDj9UTKZDa4vILuu4IZJhuj42bHIyxGHvQvKToVGq02X/BXTWHNxp0b2u0kfUn3hanCtonDvQaM1KXUffD2u52iCqPQ7OLD8tDat9aJu7YKQdwOh0srGsgqpqt7k8it91VnDUzYCD4GYa2avniuIJd28vXU8xNBOzLqqLn+V250w7zvVFYNj8pL1+Mso4PXldlEHpijogWZmkBGk93YjlUFhAq8xND71X13fekcaboX4CfhWFHMrcasBEMrw0NKwt+UZKkYQ3FxlA83zdeGkQLuMvF15Zkfu2gbd0+yvCjQg2bnjCm5j88tanR/ivhSOxM0vB67Ag1nCOQ74IqkU7qkgaO0Vqu326Q8oUHpr+xvVtzFZ3BwIiyUYbXIDHQptJJGfSYVmnISWPFoiDjqD4FCT7yJxFYMqN42ie8Z6r6EoJenQbTIWPg5nKlpXO0yhN4EMa7/damw=
before_script:
- echo $ENCRYPTION_SECRET
- echo "$ENCRYPTION_SECRET"
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in Vendor/Travis_Provisioning_Profile.mobileprovision.enc
  -d -a -out Vendor/Travis_Provisioning_Profile.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in Vendor/Certificate.cer.enc -d -a
  -out Vendor/Certificate.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in Vendor/key.p12.enc -d -a -out Vendor/key.p12
- "./Vendor/add-key.sh"
script:
- xctool "build test -sdk iphonesimulator9.2 -destination 'platform=iOS Simulator,name=iPhone5s,OS=9.2'"
after_script:
- "./Vendor/remove-key.sh"
