$:.unshift File.dirname("../.." + __FILE__)

require '../Various/version.rb'

import './Lyon/Fastfile'
import './Bruxelles/Fastfile'
import './Dublin/Fastfile'
import './Luxembourg/Fastfile'
import './Marseille/Fastfile'
import './Mulhouse/Fastfile'
import './Nantes/Fastfile'
import './Paris/Fastfile'
import './Toulouse/Fastfile'

default_platform :ios

platform :ios do

before_all do
#   increment_build_number
  # cocoapods
end

lane :appstore do

	verify_xcode

	puts "Current build version: #{getCurrentBuildVersion}"

	buildVersion = prompt(text: "Build Version: ")

	updateBuildVersion(buildVersion)

	bumpBuildNumber

	# lyon_appstore

	bruxelles_appstore



end

end
