$:.unshift File.dirname("../.." + __FILE__)

# require '../Various/version.rb'

import './Lyon/Fastfile'
import './Bruxelles/Fastfile'
import './Créteil/Fastfile'
import './Dublin/Fastfile'
import './Luxembourg/Fastfile'
import './Marseille/Fastfile'
import './Mulhouse/Fastfile'
import './Nantes/Fastfile'
import './Paris/Fastfile'
import './Toulouse/Fastfile'

default_platform :ios

platform :ios do

update_fastlane

before_all do
#   increment_build_number
  # cocoapods
end

lane :testLyon do

cp_appstore(only_lyon: true)

end

lane :cp_appstore do |actualOptions|

	is_only_lyon = actualOptions[:only_lyon]
	
	if is_only_lyon == nil
	
		puts "is nil"
	
		is_only_lyon = false
	
	else
	
		puts "not nil"
	
	end
	
	puts "only lyon #{is_only_lyon}"

	# verify_xcode

	ensure_git_branch

	ensure_git_status_clean

	currentBuildVersion = get_version_number

	Helper.log.info "Current build version: #{currentBuildVersion}"

	buildVersion = prompt(text: "Build Version: ")

	increment_version_number(version_number: buildVersion)
	
	currentBuildVersion = get_version_number
# 
# 	updateBuildVersion(buildVersion)
# 
# 	bumpBuildNumber

	increment_build_number
	
	currentBuildNumber = get_build_number

	options = {
		:automatic_release => true,
		:skip_screenshots => true
	}
	
	
	
	ENV['CP_CURRENT_VERSION'] = currentBuildVersion
	
	ENV['CP_CURRENT_BUILD'] = currentBuildNumber

	if (is_only_lyon == true)
	
		options[:is_only_lyon] = true
	
	end

	lyon_appstore(options)

	if (is_only_lyon == false)
		bruxelles_appstore(options)

		creteil_appstore(options)

		dublin_appstore(options)

		luxembourg_appstore(options)

		marseille_appstore(options)

		mulhouse_appstore(options)

		nantes_appstore(options)

		paris_appstore(options)

		toulouse_appstore(options)
	
		git_add(path: ".")

		git_commit(path: ".",
				message: "Version Bump #{currentBuildVersion} (#{currentBuildNumber})")

		add_git_tag(prefix: 'v', build_number: currentBuildNumber)

		push_to_git_remote
	
		end

end

lane :uploadSymbolsToFabric do

clean_build_artifacts

currentBuildNumber = get_build_number

ENV['DOWNLOAD_DSYMS_BUILD_NUMBER'] = "#{currentBuildNumber}"

lyon_uploadSymbolsToFabric

bruxelles_uploadSymbolsToFabric

creteil_uploadSymbolsToFabric

dublin_uploadSymbolsToFabric

luxembourg_uploadSymbolsToFabric

marseille_uploadSymbolsToFabric

mulhouse_uploadSymbolsToFabric

nantes_uploadSymbolsToFabric

paris_uploadSymbolsToFabric

toulouse_uploadSymbolsToFabric

upload_symbols_to_crashlytics

clean_build_artifacts

end

end
