# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
    "iPhone 6",
    "iPhone 6 Plus",
    "iPhone 5s",
    "iPhone 4s",
  "iPad Retina",
  "iPad Pro"
 ])

languages([
  "en-US",
  "fr-FR"
])

# clean true

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch_arguments
# launch_arguments("-favColor red")

# The name of the scheme which contains the UI Tests
scheme "aBike—Nantes"

app_identifier "com.clement.padovani.nantes"

ios_version "9.2"

configuration "Snapshots"

# Where should the resulting screenshots be stored?
output_directory "./screenshots/"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./aBike—Lyon.xcodeproj"
workspace "../../aBike—Lyon.xcworkspace"

# For more information about all available options run
# snapshot --help
